# permissions for end users to view reports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: report-viewer-role
rules:
- apiGroups:
  - gazosancontroller.k8s.io
  resources:
  - reports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gazosancontroller.k8s.io
  resources:
  - reports/status
  verbs:
  - get
