
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - developments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - gazosancontroller.k8s.io
  resources:
  - reports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gazosancontroller.k8s.io
  resources:
  - reports/status
  verbs:
  - get
  - patch
  - update
